name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrates how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
core_version_requirement: ^10.3 || ^11
dependencies:
  - 'drupal:block'
  - 'drupal:views'
  - 'webform:webform'
  - 'webform:webform_node'

# Information added by Drupal.org packaging script on 2024-08-03
version: '6.3.x-dev'
project: 'webform'
datestamp: 1722697606
